# Generated by Django 3.2.7 on 2022-03-31 16:14

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('Watermarked Image', models.ImageField(blank=True, upload_to=gallery.models.path_watermarked)),
                ('Actual Image', models.ImageField(blank=True, upload_to=gallery.models.path_no_watermark)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, default=50, null=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
    ]
