# Generated by Django 3.2.7 on 2022-03-31 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='Actual Image',
            new_name='Actual',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='Watermarked Image',
            new_name='Watermarked',
        ),
    ]
