# Generated by Django 3.2.7 on 2022-04-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
    ]
